### ISSUE TITLE
mportError: Could not import docarray python package. Please install it with pip install "langchain[docarray]"

### ISSUE THREAD

**Issue by AhmedShahhatAl** [langchain-ai/streamlit-agent#33] opened 2023-09-12 10:08 UTC
I have the problem that docarray is not compatible with pydantic as i get always the error 
ImportERROR: cannot import "ROOT_KEY" from "pydantic.main"

i tried to downgrade the pydantic to pydantic 1.10.12 but it still not working any one ahve an idea how to solve this problem?

**Comment by IlianP** [comment] 2023-09-12 14:34
duplicate of #31 ?

**Comment by sfc-gh-jcarroll** [comment] 2023-09-13 22:08
Fixed by https://github.com/langchain-ai/streamlit-agent/pull/37

**Closed by sfc-gh-jcarroll** 2023-09-13 22:08 UTC
