### ISSUE TITLE
ImportError: Could not import docarray python package. Please install it with `pip install "langchain[docarray]"`.

### ISSUE THREAD

**Issue by achilela** [langchain-ai/streamlit-agent#31] opened 2023-08-31 21:15 UTC
Hello, I tried to run 🦜 LangChain: Chat with Documents from repo and was getting this error and some other error like List has no attribute Embedding. I am just wondering if is there a bug within Langchain that requires update/upgrade? Both title Error as well the descriptive Error here in the body message have been experienced by me today.

**Comment by Tsukumizu** [comment] 2023-09-07 03:28
Try "pip install "langchain[docarray]" in your terminal, and it can be downloaded

**Comment by marcusschiesser** [comment] 2023-09-07 04:56
@Tsukumizu `langchain[docarray]` is actually already installed by poetry. @achilela's error seems to be caused by the versions of `docarray` and `pydantic` being incompatible. You can check that if you try to import `docarray`:

```
python
Python 3.11.4 (main, Jul 25 2023, 17:07:07) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import docarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcus/Library/Caches/pypoetry/virtualenvs/streamlit-agent-D1pUuZw6-py3.11/lib/python3.11/site-packages/docarray/__init__.py", line 5, in <module>
    from docarray.array import DocList, DocVec
  File "/Users/marcus/Library/Caches/pypoetry/virtualenvs/streamlit-agent-D1pUuZw6-py3.11/lib/python3.11/site-packages/docarray/array/__init__.py", line 1, in <module>
    from docarray.array.any_array import AnyDocArray
  File "/Users/marcus/Library/Caches/pypoetry/virtualenvs/streamlit-agent-D1pUuZw6-py3.11/lib/python3.11/site-packages/docarray/array/any_array.py", line 22, in <module>
    from docarray.base_doc import BaseDoc
  File "/Users/marcus/Library/Caches/pypoetry/virtualenvs/streamlit-agent-D1pUuZw6-py3.11/lib/python3.11/site-packages/docarray/base_doc/__init__.py", line 1, in <module>
    from docarray.base_doc.any_doc import AnyDoc
  File "/Users/marcus/Library/Caches/pypoetry/virtualenvs/streamlit-agent-D1pUuZw6-py3.11/lib/python3.11/site-packages/docarray/base_doc/any_doc.py", line 3, in <module>
    from .doc import BaseDoc
  File "/Users/marcus/Library/Caches/pypoetry/virtualenvs/streamlit-agent-D1pUuZw6-py3.11/lib/python3.11/site-packages/docarray/base_doc/doc.py", line 22, in <module>
    from pydantic.main import ROOT_KEY
ImportError: cannot import name 'ROOT_KEY' from 'pydantic.main' (/Users/marcus/Library/Caches/pypoetry/virtualenvs/streamlit-agent-D1pUuZw6-py3.11/lib/python3.11/site-packages/pydantic/main.py)
```

**Comment by marcusschiesser** [comment] 2023-09-07 05:08
A quick workaround is to downgrade `pydantic` from major version 2 to major 1:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index 86089bd..28184ad 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -19,6 +19,7 @@ tabulate = "^0.9.0"
 streamlit-feedback = "^0.0.9"
 langchain-experimental = "^0.0.10"
 streamlit= ">=1.26"
+pydantic = "^1.0.0"
 
 [tool.poetry.group.dev.dependencies]
 black = "^23.3.0"
```

**Comment by AhmedShahhatAl** [comment] 2023-09-12 09:59
@marcusschiesser can you give me the exact steps because i have the same problem, which version of pydantic you used? and which version of docarray you have ?

**Comment by Harry969** [comment] 2023-09-12 11:12
` [tool.poetry]
name = "streamlit-agent"
version = "0.1.0"
description = ""
authors = ["Tim Conkling <tconkling@gmail.com>", "Joshua Carroll <joshua.carroll@snowflake.com>"]
license = "Apache 2.0"
readme = "README.md"
packages = [{include = "streamlit_agent"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
langchain = {version = ">=0.0.252", extras = ["docarray"]}
openai = "^0.27.8"
duckduckgo-search = "^3.8.3"
pypdf = "^3.12.2"
sentence-transformers = "^2.2.2"
torch = ">=2.0.0, !=2.0.1"
tabulate = "^0.9.0"  
streamlit-feedback = "^0.0.9"
langchain-experimental = "^0.0.10"
streamlit= ">=1.26"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4.1"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
`Hello, I modified pyproject.toml according to the method you provided and reconfigured the corresponding version of the package, but the error may be a version compatibility issue.`PS C:\Users\39627\Downloads\streamlit-agent-main> & c:/Users/39627/Downloads/streamlit-agent-main/langchain_env/Scripts/python.exe c:/Users/39627/Downloads/streamlit-agent-main/streamlit_agent/chat_with_documents.py
Traceback (most recent call last):
  File "c:\Users\39627\Downloads\streamlit-agent-main\streamlit_agent\chat_with_documents.py", line 4, in <module>
    from langchain.chat_models import ChatOpenAI
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\__init__.py", line 6, in <module>       
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\agents\__init__.py", line 31, in <module>
    from langchain.agents.agent import (
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\agents\agent.py", line 14, in <module>  
    from langchain.agents.agent_iterator import AgentExecutorIterator
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\agents\agent_iterator.py", line 21, in <module>
    from langchain.callbacks.manager import (
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\callbacks\__init__.py", line 10, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler 
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\callbacks\aim_callback.py", line 5, in <module>
    from langchain.schema import AgentAction, AgentFinish, LLMResult
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\schema\__init__.py", line 3, in <module>
    from langchain.schema.cache import BaseCache
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\schema\cache.py", line 6, in <module>   
    from langchain.schema.output import Generation
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\schema\output.py", line 7, in <module>  
    from langchain.load.serializable import Serializable
  File "C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\load\serializable.py", line 4, in <module>
    from langchain.pydantic_v1 import BaseModel, PrivateAttr        
ImportError: cannot import name 'PrivateAttr' from 'langchain.pydantic_v1' (C:\Users\39627\Downloads\streamlit-agent-main\langchain_env\Lib\site-packages\langchain\pydantic_v1\__init__.py)`

**Comment by sfc-gh-jcarroll** [comment] 2023-09-13 22:07
Fixed with https://github.com/langchain-ai/streamlit-agent/pull/37

Thanks @marcusschiesser for the tip on pinning pydantic. Sorry for the delay on a fix here.

**Closed** 2023-09-13 22:07 UTC
